// front-end/src/components/KotPrint.vue
<template>
  <div>
    <header>
      <p class="text-h2 font-weight-black text-right">{{ cartName }}</p>
      <p class="text-h5 text-bold" v-if="orderReference">
        Order# {{ orderReference }}
      </p>
    </header>
    <main>
      <v-table>
        <thead>
          <tr>
            <td>Item</td>
            <td class="text-right">Quantity</td>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in items" :key="item.id">
            <td>
              {{ item.name }}
            </td>
            <td>
              <span
                class="old quantity"
                v-if="
                  item.quantity !== item.previousQuantity &&
                  item.previousQuantity !== undefined &&
                  item.previousQuantity !== 0
                "
                >{{ item.previousQuantity }}</span
              >
              <span
                class="quantity"
                :class="{
                  changed: item.quantity !== item.previousQuantity,
                }"
              >
                {{ item.quantity }}
              </span>
            </td>
          </tr>
        </tbody>
      </v-table>
    </main>
    <div v-if="customerNote" class="my-4 mx-2 pa-2 customer-note">
      {{ customerNote }}
    </div>
  </div>
</template>

<script lang="ts">
export default {
  data: () => ({}),
  props: {
    cartName: {
      type: String,
      required: true,
    },
    orderReference: {
      type: String,
      required: true,
    },
    customerNote: {
      type: String,
      required: false,
    },
    items: {
      type: Array<{
        id: number;
        name: string;
        quantity: number;
        previousQuantity?: number;
      }>,
      required: true,
    },
  },
};
</script>

<style scoped>
* {
  color: black !important;
  word-break: keep-all;
}
header {
  text-align: center;
}

tbody tr td {
  border-bottom: 2px solid black !important;
}

tr td:last-child {
  text-align: right;
}

.quantity {
  display: inline-block;
  padding: 4px;
  min-width: 1em;
  margin-left: 4px;
}

.changed {
  border: 1px solid black;
  border-radius: 100%;
  min-width: 1em;
  margin-left: 4px;
}

.old {
  text-decoration: line-through;
}

.customer-note {
  border: 2px solid black;
}
</style>

// components/print/KotPrint.tsx
'use client';

import { PrintJobData } from '@/stores/print';

interface KotPrintProps {
  data: PrintJobData;
}

export default function KotPrint({ data }: KotPrintProps) {
  const {
    kotItems = [],
    orderReference,
    frontendId,
    cartName,
    customerNote,
  } = data;

  // Use frontend ID as primary order identifier, fall back to orderReference for legacy orders
  const displayOrderNumber = frontendId || orderReference;

  return (
    <div className="kot-print">
      {/* Header */}
      <header>
        <p className="cart-name">{cartName}</p>
        {displayOrderNumber && (
          <p className="order-ref">Order# {displayOrderNumber}</p>
        )}
      </header>

      {/* Items Table */}
      <main>
        <table className="kot-items">
          <thead>
            <tr>
              <td>Item</td>
              <td className="text-right">Qty</td>
            </tr>
          </thead>
          <tbody>
            {kotItems.map(item => {
              // Truly new item: not in previous KOT at all
              const isTrulyNewItem = item.previousQuantity === undefined;
              // Item was previously removed (quantity was 0) and is being re-added
              const wasRemoved = item.previousQuantity === 0;
              // Item existed before with quantity > 0
              const hadPrevious = item.previousQuantity !== undefined && item.previousQuantity > 0;
              // Quantity has changed from a previous non-zero value
              const hasQuantityChanged = hadPrevious && item.quantity !== item.previousQuantity;
              // Item is being removed
              const isRemoved = item.quantity === 0 && hadPrevious;
              // Show as bold (new items, changed quantity, removed items)
              const shouldBold = isTrulyNewItem || wasRemoved || hasQuantityChanged || isRemoved;

              return (
                <tr key={item.id} className={`${isRemoved ? 'removed-item' : ''} ${shouldBold ? 'bold-row' : ''}`}>
                  <td className={isRemoved ? 'strikethrough' : ''}>{item.name}</td>
                  <td className="quantity-cell">
                    {(hasQuantityChanged || isRemoved) ? (
                      <>
                        <span className="old-quantity">{item.previousQuantity}</span>
                        <span className="arrow">&gt;</span>
                        <span className="new-quantity">{isRemoved ? 'X' : item.quantity}</span>
                      </>
                    ) : (
                      <span className="quantity">{item.quantity}</span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </main>

      {/* Customer Note */}
      {customerNote && (
        <div className="customer-note">
          {customerNote}
        </div>
      )}

      <style jsx>{`
        .kot-print {
          font-family: monospace;
          color: black;
          background: white;
          padding: 8px;
        }

        .kot-print * {
          color: black !important;
        }

        header {
          text-align: center;
          margin-bottom: 12px;
        }

        .cart-name {
          font-size: 32px;
          font-weight: 900;
          text-align: right;
        }

        .order-ref {
          font-size: 18px;
          font-weight: bold;
        }

        .server-ref {
          font-size: 12px;
          color: #666;
          margin-top: 2px;
        }

        .kot-items {
          width: 100%;
          border-collapse: collapse;
        }

        .kot-items thead td {
          border-bottom: 2px solid black;
          padding-bottom: 4px;
          font-weight: bold;
        }

        .kot-items tbody tr td {
          border-bottom: 2px solid black;
          padding: 8px 0;
          vertical-align: middle;
        }

        .quantity-cell {
          text-align: right;
        }

        .quantity {
          display: inline-block;
          padding: 4px;
          min-width: 1em;
          margin-left: 4px;
        }

        .old-quantity {
          margin-right: 2px;
          opacity: 0.6;
        }

        .arrow {
          margin: 0 2px;
          opacity: 0.6;
        }

        .new-quantity {
          font-weight: 900;
          margin-left: 2px;
        }

        .strikethrough {
          text-decoration: line-through;
          opacity: 0.6;
        }

        .removed-item {
          opacity: 0.7;
        }

        .bold-row td {
          font-weight: bold;
        }

        .customer-note {
          margin-top: 16px;
          padding: 8px;
          border: 2px solid black;
        }
      `}</style>
    </div>
  );
}
