// next/components/print/BillPrint.tsx
'use client';

import { PrintJobData } from '@/stores/print';

interface BillPrintProps {
  data: PrintJobData;
}

export default function BillPrint({ data }: BillPrintProps) {
  const {
    items = [],
    customer,
    orderReference,
    orderTime,
    payment = 0,
    discountTotal = 0,
    cartName,
  } = data;

  const filteredItems = items.filter(item => item.quantity > 0);

  const subtotal = filteredItems.reduce(
    (total, item) => total + item.price * item.quantity,
    0
  );

  const total = subtotal - discountTotal;
  const change = payment - total;

  const formatCurrency = (amount: number) => amount.toFixed(0);

  const formatDate = (dateStr?: string) => {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-GB');
  };

  const formatTime = (dateStr?: string) => {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    return date.toLocaleTimeString();
  };

  const humanizeCartName = (name?: string) => {
    if (!name) return '';
    if (/T[^a-zA-Z]/g.test(name)) return 'Table ' + name.slice(2);
    if (/D[^a-zA-Z]/g.test(name)) return 'Home Delivery';
    if (/P[^a-zA-Z]/g.test(name)) return 'Take away';
    return name;
  };

  const complexItemName = (name: string) => {
    const parts = name.split(':').map(part => part.trim());
    const subItems = parts.length > 1
      ? parts[1].split(',').map(part => part.trim())
      : [];
    return { name: parts[0], subItems };
  };

  const hasCustomerInfo = customer && (customer.name || customer.phone);

  return (
    <div className="bill-print">
      {/* Header with Logo */}
      <header className="brand">
        <div className="logo">
          {/* Logo placeholder - replace with your logo */}
          <svg viewBox="0 0 100 40" className="w-1/2 mx-auto">
            <text x="50" y="30" textAnchor="middle" className="text-xl font-bold">LOGO</text>
          </svg>
        </div>
        <p className="text-xs mb-2">
          <strong>Phone:</strong> 01765553555 <br />
          Girls School Road, Chhatak, Sunamganj
        </p>
      </header>

      {/* Order Info */}
      {filteredItems.length > 0 && (
        <header className="order-info">
          <p className="my-1 text-sm">
            {humanizeCartName(cartName)}
            {hasCustomerInfo && (
              <>
                <br />
                <span>
                  {customer?.name}
                  {customer?.name && customer?.phone && ' | '}
                  {customer?.phone}
                </span>
              </>
            )}
          </p>
          <p className="text-sm my-1">Invoice#: {orderReference}</p>
          <p className="text-sm my-1">
            Date: <strong>{formatDate(orderTime)}</strong>{' '}
            Time: <strong>{formatTime(orderTime)}</strong>
          </p>
        </header>
      )}

      {/* Line Items */}
      {filteredItems.length > 0 && (
        <main>
          <table className="line-items">
            <thead>
              <tr>
                <td className="pr-1 text-left">Item</td>
                <td className="px-1">Qty</td>
                <td className="px-1">Price</td>
                <td className="pl-1 text-right">T.Price</td>
              </tr>
            </thead>
            <tbody>
              {filteredItems.map(item => {
                const { name, subItems } = complexItemName(item.name);
                return (
                  <tr key={item.id}>
                    <td className="pr-1">
                      {name}
                      {subItems.length > 0 && (
                        <ul className="ml-4">
                          {subItems.map((subItem, idx) => (
                            <li key={idx}>{subItem}</li>
                          ))}
                        </ul>
                      )}
                    </td>
                    <td className="px-1">{item.quantity}</td>
                    <td className="px-1 text-right">{formatCurrency(item.price)}</td>
                    <td className="pl-1 text-right">{formatCurrency(item.price * item.quantity)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>

          <hr className="my-2 border-dashed" />

          {/* Summary */}
          <table className="receipt-summary text-sm">
            <tbody>
              {discountTotal > 0 && (
                <tr>
                  <td className="w-full">Discount</td>
                  <td className="text-right">-{formatCurrency(discountTotal)}</td>
                </tr>
              )}
              <tr>
                <td className="w-full">Total</td>
                <td className="text-right font-bold">{formatCurrency(total)}</td>
              </tr>
              {payment > 0 && (
                <>
                  <tr>
                    <td className="w-full">Payment</td>
                    <td className="text-right">{formatCurrency(payment)}</td>
                  </tr>
                  <tr>
                    <td className="w-full">Change</td>
                    <td className="text-right">{formatCurrency(change)}</td>
                  </tr>
                </>
              )}
            </tbody>
          </table>
        </main>
      )}

      {/* Footer */}
      <footer className="mt-4">
        <p className="text-xs">
          Online menu: <strong>www.mycozy.cafe/menu</strong>
          <br />
          Call us for home delivery!
        </p>
      </footer>

      <style jsx>{`
        .bill-print {
          font-family: monospace;
          color: black;
          background: white;
          padding: 8px;
        }

        .bill-print * {
          color: black !important;
        }

        .brand {
          text-align: center;
          border-bottom: 1px dashed black;
          padding-bottom: 8px;
          margin-bottom: 8px;
        }

        .order-info {
          text-align: center;
          margin-bottom: 8px;
        }

        .line-items {
          width: 100%;
          font-size: 12px;
        }

        .line-items thead tr td {
          border-bottom: 1px solid black;
          padding-bottom: 4px;
        }

        .line-items tbody tr td {
          padding: 2px 0;
          vertical-align: top;
        }

        .receipt-summary {
          width: 100%;
        }

        .receipt-summary td {
          padding: 2px 0;
        }

        footer {
          text-align: center;
          border-top: 1px dashed black;
          padding-top: 8px;
        }
      `}</style>
    </div>
  );
}

// front-end/src/components/BillPrint.vue
<template>
  <div>
    <header class="brand">
      <div class="logo">
        <logo-component />
      </div>

      <p class="text-caption mb-2">
        <strong>Phone: </strong> 01765553555 <br />
        Girls School Road, Chhatak, Sunamganj
      </p>
    </header>
    <header v-if="filteredCartItems.length > 0">
      <p class="my-1 text-body-2">
        {{ humanizedCartName }}
        <br v-if="hasCustomerInfo" />
        <span v-if="hasCustomerInfo">
          {{ customer.name }}
          <span v-if="customer.name && customer.phone"> | </span>
          {{ customer.phone }}
        </span>
      </p>
      <p class="text-body-2 my-1">Invoice#: {{ invoiceNumber }}</p>
      <p class="text-body-2 my-1">
        Date: <strong>{{ orderVisibleDate }}</strong> Time:
        <strong>{{ orderVisibleTime }}</strong>
      </p>
    </header>
    <main v-if="filteredCartItems.length > 0">
      <table class="line-items text-caption mt-2">
        <thead>
          <tr>
            <td class="pr-1 text-left">Item</td>
            <td class="px-1">Qty</td>
            <td class="px-1">Price</td>
            <td class="pl-1 text-right">T.Price</td>
          </tr>
        </thead>
        <tbody>
          <tr v-for="cartItem in filteredCartItems" :key="cartItem.id">
            <td class="pr-1">
              {{ complexItemName(cartItem).name }}
              <ul
                v-for="subItem in complexItemName(cartItem).subItems"
                :key="subItem"
              >
                <li>{{ subItem }}</li>
              </ul>
            </td>
            <td class="px-1">{{ cartItem.quantity }}</td>
            <td class="px-1 text-right">
              {{ formatCurrency(cartItem.price) }}
            </td>
            <td class="pl-1 text-right total-column">
              {{ formatCurrency(cartItem.price * cartItem.quantity) }}
            </td>
          </tr>
        </tbody>
      </table>

      <v-divider></v-divider>

      <table class="receipt-summary mt-2 text-body-2">
        <tbody>
          <tr v-if="discountTotal > 0">
            <td class="w-100">Discount</td>
            <td>{{ formatCurrency(-discountTotal) }}</td>
          </tr>
          <tr>
            <td class="w-100">Total</td>
            <td>
              <strong>{{ formatCurrency(subtotal) }}</strong>
            </td>
          </tr>
          <tr v-if="payment">
            <td class="w-100">Payment</td>
            <td>{{ formatCurrency(payment) }}</td>
          </tr>
          <tr v-if="payment">
            <td class="w-100">Change</td>
            <td>{{ formatCurrency(-remainingAmount) }}</td>
          </tr>
        </tbody>
      </table>
    </main>
    <footer class="mt-4">
      <p class="text-caption">
        Online menu: <strong>www.mycozy.cafe/menu</strong>
        <br />
        Call us for home delivery!
      </p>
    </footer>
  </div>
</template>

<script>
import LogoComponent from "./LogoComponent.vue";

export default {
  components: {
    LogoComponent,
  },
  props: [
    "items",
    "customer",
    "invoiceNumber",
    "orderTime",
    "payment",
    "discountTotal",
    "cartName",
  ],
  computed: {
    subtotal() {
      return Object.values(this.items).reduce(
        (total, item) => total + item.price * item.quantity,
        0
      );
    },

    remainingAmount() {
      return this.payment - this.subtotal;
    },

    filteredCartItems() {
      return Object.values(this.items).filter((item) => item.quantity > 0);
    },

    formattedDiscount() {
      if (this.discount.type === "percent") {
        return this.discount.value + "%";
      } else {
        return this.discount.value;
      }
    },

    hasCustomerInfo() {
      return this.customer && (this.customer.name || this.customer.phone);
    },

    humanizedCartName() {
      if (/T[^a-zA-Z]/g.test(this.cartName)) {
        return "Table " + this.cartName.slice(2);
      } else if (/D[^a-zA-Z]/g.test(this.cartName)) {
        return "Home Delivery";
      } else if (/P[^a-zA-Z]/g.test(this.cartName)) {
        return "Take away";
      }

      return this.cartName;
    },

    orderVisibleDate() {
      return new Date(this.orderTime).toLocaleDateString("en-GB");
    },

    orderVisibleTime() {
      return new Date(this.orderTime).toLocaleTimeString();
    },
  },
  methods: {
    complexItemName(item) {
      const parts = item.name.split(":").map((part) => part.trim());
      let subItems = [];
      if (parts.length > 1) {
        subItems = parts[1].split(",").map((part) => part.trim());
      }
      return {
        name: parts[0],
        subItems,
      };
    },

    formatCurrency(amount) {
      return amount.toFixed(0);
    },
  },
};
</script>

<style scoped>
* {
  color: black !important;
  word-break: keep-all;
}
.logo svg {
  width: 50%;
  height: 60%;
}
header {
  text-align: center;
}

.brand {
  border-bottom: 1px dashed black;
}

.line-items {
  width: 100%;
}

.line-items thead tr:last-child td {
  border-bottom: 1px solid black;
}

.receipt-summary td:nth-child(2) {
  text-align: right;
}

.m-0 {
  margin: 0;
}

ul {
  margin-left: 1em;
}
</style>
