// next/components/print/ThermalPrint.tsx
'use client';

import { useEffect, useRef } from 'react';
import { usePrintStore, isElectron } from '@/stores/print';
import BillPrint from './BillPrint';
import KotPrint from './KotPrint';

export default function ThermalPrint() {
  const { queue, currentJob, config, pop, setProcessing, isProcessing } = usePrintStore();
  const printAreaRef = useRef<HTMLDivElement>(null);

  // Get printer name based on job type
  const getPrinterName = (type: 'bill' | 'kot' | 'drawer'): string => {
    switch (type) {
      case 'drawer':
        return config.drawerPrinter;
      case 'kot':
        return config.kitchenPrinter;
      default:
        return config.billPrinter;
    }
  };

  // Execute print
  const executePrint = async () => {
    if (!currentJob || isProcessing) return;

    setProcessing(true);

    const { type, data } = currentJob;

    // Handle drawer separately
    if (type === 'drawer') {
      if (isElectron()) {
        window.electron!.openDrawer(getPrinterName('drawer'));
      } else {
        console.log('[Print] Cash drawer kick (dev mode)');
      }
      setTimeout(() => pop(), 500);
      return;
    }

    // For bill/kot, wait for render then print
    await new Promise(resolve => setTimeout(resolve, 100));

    if (isElectron() && config.enablePrinting) {
      // Electron printing
      window.electron!.print({
        deviceName: getPrinterName(type),
        silent: config.silentPrinting,
        pageSize: {
          width: config.printWidth * 1000,
          height: config.printHeight * 1000,
        },
      });

      // Wait for print to complete
      setTimeout(() => pop(), 1500);
    } else {
      // Browser/dev mode
      if (config.enablePrinting) {
        // Use browser print dialog
        window.onafterprint = () => {
          window.onafterprint = null;
          pop();
        };
        window.print();
      } else {
        // Dev mode - just log
        console.log('[Print]', {
          type,
          printer: getPrinterName(type),
          data,
        });
        pop();
      }
    }
  };

  // Watch for new jobs
  useEffect(() => {
    if (currentJob && !isProcessing) {
      executePrint();
    }
  }, [currentJob, isProcessing]);

  // Render nothing if no job or drawer type
  if (!currentJob || currentJob.type === 'drawer') {
    return null;
  }

  return (
    <div
      ref={printAreaRef}
      id="print-area"
      style={{ width: `${config.printWidth}mm` }}
      className="print-only"
    >
      {currentJob.type === 'bill' && currentJob.data && (
        <BillPrint data={currentJob.data} />
      )}
      {currentJob.type === 'kot' && currentJob.data && (
        <KotPrint data={currentJob.data} />
      )}

      <style jsx global>{`
        /* Hide print area on screen */
        #print-area {
          display: none;
        }

        /* Show only print area when printing */
        @media print {
          body * {
            visibility: hidden;
          }

          #print-area,
          #print-area * {
            visibility: visible;
          }

          #print-area {
            display: block !important;
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }

          @page {
            margin: 0;
            size: auto;
          }
        }
      `}</style>
    </div>
  );
}

// front-end/src/components/ThermalPrint.vue
<template>
  <div
    id="print-area"
    :style="{ width: `${printWidth}mm` }"
    class="d-print-block d-none"
  >
    <bill-print
      v-if="printType === 'bill'"
      :items="printData.items"
      :customer="printData.customer"
      :order-reference="printData.invoiceNumber"
      :order-time="printData.orderTime"
      :payment="printData.payment"
      :discount-total="printData.discountTotal"
      :cart-name="printData.cartName"
    />
    <kot-print
      v-if="printType === 'kot'"
      :items="printData.kotItems"
      :order-reference="printData.invoiceNumber"
      :cart-name="printData.cartName"
    />
  </div>
</template>

<script lang="ts">
import BillPrint from "@/components/BillPrint.vue";
import KotPrint from "@/components/KotPrint.vue";
import config from "@/utils/config";
import { defineComponent } from "vue";
import { mapActions, mapState } from "pinia";
import { usePrintStore } from "@/stores/print";

export default defineComponent({
  name: "ThermalPrint",

  components: {
    BillPrint,
    KotPrint,
  },
  data() {
    return {
      printType: undefined as "bill" | "kot" | "drawer" | undefined,
      printData: null as any,
    };
  },

  watch: {
    nextJob: {
      handler() {
        this.handleJob();
      },
      immediate: true,
    },
  },

  computed: {
    ...mapState(usePrintStore, ["nextJob"]),

    printWidth() {
      return config.printWidth;
    },
  },

  methods: {
    ...mapActions(usePrintStore, ["pop", "push"]),
    async handleJob() {
      if (this.nextJob === undefined) {
        this.printType = undefined;
        return;
      }
      this.printType = this.nextJob?.type;
      this.printData = this.nextJob?.data;
      await this.$nextTick();
      await this.printReceipt();
      this.pop();
    },

    getPrinterName(): string {
      switch (this.printType) {
        case "drawer":
          return config.drawerPrinter;
        case "kot":
          return config.kitchenPrinter;
        default:
          return config.billPrinter;
      }
    },

    printReceipt() {
      return new Promise<void>((resolve) => {
        if (window.electron) {
          window.electron.print({
            ...config.printerConfig,
            deviceName: this.getPrinterName(),
            silent: config.silentPrinting,
            pageSize: {
              width: parseInt(config.printWidth) * 1000,
              height: parseInt(config.printHeight) * 1000,
            },
          });
          setTimeout(() => {
            // Give it some time to print
            resolve();
          }, 1000);
        } else {
          window.onafterprint = () => {
            window.onafterprint = null;
            resolve();
          };
          window.print();
        }
      });
    },
  },
});
</script>

<style>
#print-area > * {
  width: 100%;
}
</style>
